name: Publish

on:
  push:
    tags: ["v[0-9]*"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

  npm:
    name: npm
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install
        run: npm ci

      - name: Publish
        run: npm publish --access public
